Homepage rtk
ravgusha/phone-book pull request #2
Opened 2022-07-16 20:22 UTC by ravgusha

2022-07-18 12:35 UTC, ILokalin requested changes

2022-07-18 12:35 UTC, ILokalin commented on src/App.css
> +/* Убираем внешние отступы */
Отлично, что сброшены стили и мне кажется что в файле App немного выше уровень абстракции - что-то важное для структуры приложения. Как думаешь, может лучше подключить файл reset.css и этим можно будет решить два важных вопроса:
- разделить абстракции
- исключить комментарии, так как название файла будет в полной мере сообщать о своем назначении

2022-07-18 12:35 UTC, ILokalin commented on src/App.tsx
> +import { Provider } from 'react-redux';
Удобно, когда первыми подключены библиотеки, после компоненты и файлы из текущего контейнера. Да, перфекционизм он такой :smirk:

2022-07-18 12:35 UTC, ILokalin commented on src/components/Contact/Contact.tsx
> +        <button onClick={() => openPopup(person.id)}>Edit</button>
Сможем ли здесь использовать ссылку вместо кнопки? Переходы на адрес принято оформлять ссылкой. Кнопка, обычно, запускает скрипт без перехода.

2022-07-18 12:35 UTC, ILokalin commented on src/components/Contact/Contact.tsx
> +      <td>{person.firstName}</td>
Предлагаю деструктурировать `person`.

2022-07-18 12:35 UTC, ILokalin commented on src/components/Contact/Contact.tsx
> +        <a href="#">Delete</a>
Для удаления больше подойдет кнопка - так как нет перехода по ссылке

2022-07-18 12:35 UTC, ILokalin commented on src/components/ContactList/ContactList.tsx
> +import Contact from '../Contact/Contact';
Если именовать основной файл index, то можно будут импортировать более кратко и без повторения сущности:
```
import Contact from '../Contact';
```
Обычно избегаем повторений в именованиях. В папке могут быть другие файлы - пример:
```
import { nameAccessor } from '../Contact/accessors'; // 
```

2022-07-18 12:35 UTC, ILokalin commented on src/components/ContactList/ContactList.tsx
> +const StyledTable = styled.table`
Большие стили лучше вынести в отдельный файл - так разделяем абстракции и акцентируем внимание на важном:
- стили в файле style.ts
- компонент в файле index.ts

2022-07-18 12:35 UTC, ILokalin commented on src/components/ContactList/ContactList.tsx
> +        <StyledTable>
Подход верный, но в таком варианте контейнер оперирует большим числом сущностей:
- в нем стили
- в нем таблица
- и что-то важное для получения данных

Если выделить таблицу в компоненты? Таблице давать опции:
- формат колонок
- набор данных

```
<Table 
  columns={columns}
  data={data}
/>
```
Может какие-то пропсы понадобятся еще.

2022-07-18 12:35 UTC, ILokalin commented on src/components/Header/Header.tsx
> +const MainButton = styled.button`
Кнопка - это отдельный компонент

2022-07-18 12:35 UTC, ILokalin commented on src/components/Header/Header.tsx
> +const MainButton = styled.button`
Да, может уточнить что такое "главная" кнопка? Не открывая проект, не совсем понятно :worried:

2022-07-18 12:35 UTC, ILokalin commented on src/components/ContactList/ContactList.tsx
> +  const contacts = useSelector((state: IState) => state.contacts);
Если это компонент, то не стоит в нем добавлять получение данных. Компонент лучше делать максимально простым - он не должен знать о том, как получать данные: получает их в пропсах и если нужно что-то передать, то вызывает колбек

2022-07-18 12:35 UTC, ILokalin commented on src/containers/AddContact/index.tsx
> +const AddPage = () => {
Удобно придерживаться одной структуры:
```
ИмяКонтейнера
  Form
    index.ts
  index.ts
```
 В таком случае будет проще выделять визуально файлы, не зависимо от того, в каком контейнере находимся.

2022-07-18 12:35 UTC, ILokalin commented on src/containers/AddContact/index.tsx
> +const AddPage = () => {
Лучше не использовать синонимы для сущностей - рано или поздно они кончатся и могут путать.
Контейнер AddContact, а компонент AddPage, в презентации укажем "форма добавления" и новый разработчик, читая код начинает путаться.

Если контейнер ContactPage, то в файле index компонент `ContactPage`, в форме компонент `ContactForm`.

2022-07-18 12:35 UTC, ILokalin commented on src/containers/AddContact/index.tsx
> +    <>
Лучше использовать <Fragment> - удобнее для чтения и выглядит более стильно.

2022-07-18 12:35 UTC, ILokalin commented on src/containers/AddContact/index.tsx
> +      <Header />
У формы есть шапка? Если это шапка приложения, то она должна находиться в основном файле с приложением - здесь только форма

2022-07-18 12:35 UTC, ILokalin commented on src/containers/AddContact/index.tsx
> +      <Container>
Контейнер тоже должен быть в одном файле - к нему подкидываем содержимое (страницы, их формы)

2022-07-18 12:35 UTC, ILokalin commented on src/containers/AddContact/index.tsx
> +          <Input placeholder="First name" {...register('firstName', { required: true })} />
Скорее всего, для инпута нужен лейбл - и вместе, это компонент `FormInput`

2022-07-18 12:35 UTC, ILokalin commented on src/containers/AddContact/index.tsx
> +          {errors.firstName?.type === 'required' && <Error>First name is required</Error>}
Сообщение об ошибке - это отдельный компонент, который подключается в компоненте FormInput. На уровне формы мы отправляем errors, а компонент отображает ошибки, если совпадает имя. Это может выглядеть так:
```
<FormInput
  value={value}
  name={ATTRIBUTE_PHONE}
  errors={errors}
  label={LABEL_PHONE}
  isRequire
  handleInputChange={/** функция обработчик**/}
/>
```

2022-07-18 12:35 UTC, ILokalin commented on src/containers/AddContact/index.tsx
> +              pattern: /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/,
Отлично, что использовано регулярное выражение и было бы классно его назвать - определить в переменной и в имени уточнить, "что делает" это выражение.

2022-07-18 12:35 UTC, ILokalin commented on src/containers/AddContact/index.tsx
> +          {errors.phone?.type === 'required' && <Error>Phone is required</Error>}
Список возможных ошибок может быть большим - лучше организовать хранение всех ошибок в массиве и указывать имя "для кого они". Поле проверяет список и если есть его имя, показывает ошибку.

Может возникнуть ситуация, когда для одного поля несколько ошибок - перед сохранением их в массиве, валидатор должен объединить ошибки с одним именем в одну строку.

2022-07-18 12:35 UTC, ILokalin commented on src/containers/Contacts/index.tsx
> +const HomePage = () => {
Здесь необходимо поработать над структурой: имя компонента лучше называться именем контейнера, именно в этом компоненте было бы здорово получать данные (так как он является контейнером). 

Не выделял бы HomePage - так как если добавить аутентификацию и права пользователей, то для каждого будет своя стартовая страница (у кого-то страница логина, у кого-то нет доступа к контактам). Чем меньше сущностей, тем проще их контролировать - сущность "HomePage" избыточна и не несет особой миссии.

2022-07-18 12:35 UTC, ILokalin commented on src/containers/EditContact/index.tsx
> +  return <div>ddjgn;oldjfgodjgfd jldj dj;lgjdl;fgj djg ;ldjdl;fjgd</div>;
Загадочный код... Отмечу важный момент - стоит использовать одну форму для добавления и редактирования. Удобно тем, что не будет повторяющегося кода

2022-07-18 12:35 UTC, ILokalin commented on src/index.tsx
>  import reportWebVitals from './reportWebVitals';
Уточню - это используется?

2022-07-18 12:35 UTC, ILokalin commented on src/redux/configureStore.ts
> +export default store;
Необходимо проверить файл/проект линтером. Общепринято, оставлять одну пустую строку в конце js или ts файла
![image](https://user-images.githubusercontent.com/51790923/179379639-a6d35ebe-6060-4705-b650-45db7b56dcad.png)

2022-07-18 12:35 UTC, ILokalin commented on src/redux/types.ts
> +import { IPerson } from "../types";
Предложил бы описывать данные начиная с API - вот место, где мы их получаем и храним, здесь первичные интерфейсы. Далее, они могут использоваться на уровнях выше.

Сейчас мы делаем приложение "записная книжка", но блок работы с данными не должен быть самой важной структурой... завтра добавим плейер или лунный календарь - каждая структура данных должна определяться в своем месте: контакты в месте хранения контактов, календарь в календаре, и т.д.

2022-07-18 12:35 UTC, ILokalin commented on src/components/Contact/Contact.tsx
> +      <td>{person.firstName}</td>
Наверно, это не актуально здесь. Ниже будет предложение, выделить таблицу как компонент и ей передавать данные, сообщать как с ними работать.

2022-07-18 12:35 UTC, ILokalin commented on src/components/Contact/Contact.tsx
> +      <td>{person.firstName}</td>
Да, можно подключить библиотеку React Table

2022-07-18 13:00 UTC, ravgusha commented on src/App.css
> +/* Убираем внешние отступы */
создала reset.css, перенесла туда обнуляющие стили

2022-07-18 14:24 UTC, ravgusha commented on src/App.tsx
> +import { Provider } from 'react-redux';
Поправила

2022-07-18 14:27 UTC, ravgusha commented on src/components/Contact/Contact.tsx
> +        <button onClick={() => openPopup(person.id)}>Edit</button>
сменила `<button> `на `<a>`

2022-07-18 14:28 UTC, ravgusha commented on src/components/Contact/Contact.tsx
> +        <a href="#">Delete</a>
Сделала кнопку

2022-07-18 14:30 UTC, ravgusha commented on src/containers/EditContact/index.tsx
> +  return <div>ddjgn;oldjfgodjgfd jldj dj;lgjdl;fgj djg ;ldjdl;fjgd</div>;
Добавила форму для редактирования контакта

2022-07-20 09:08 UTC, ravgusha commented on src/index.tsx
>  import reportWebVitals from './reportWebVitals';
Нет, удалила reportWebVitals

2022-07-20 09:09 UTC, ravgusha commented on src/redux/configureStore.ts
> +export default store;
Добавила правило в линтер

2022-07-20 09:29 UTC, ravgusha commented on src/components/ContactList/ContactList.tsx
> +import Contact from '../Contact/Contact';
переименовала в index

2022-07-20 09:37 UTC, ravgusha commented on src/containers/AddContact/index.tsx
> +              pattern: /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/,
вынесла в переменную

2022-07-20 20:31 UTC, ravgusha commented on src/components/Contact/Contact.tsx
> +      <td>{person.firstName}</td>
подключила react-table

2022-07-20 20:31 UTC, ravgusha commented on src/components/ContactList/ContactList.tsx
> +const StyledTable = styled.table`
вынесла стили в отельный файл

2022-07-20 20:39 UTC, ravgusha commented on src/containers/Contacts/index.tsx
> +const HomePage = () => {
перенесла получение данных в этот файл

2022-07-20 20:42 UTC, ravgusha commented on src/components/ContactList/ContactList.tsx
> +  const contacts = useSelector((state: IState) => state.contacts);
Данный компонент удалила, вместо него ContactTable. получение данных теперь в контейнере, а не в компоненте

2022-07-20 20:45 UTC, ravgusha commented on src/components/ContactList/ContactList.tsx
> +        <StyledTable>
Вынесла таблицу в отдельный компонент Table

2022-07-21 17:55 UTC, ravgusha commented on src/containers/AddContact/index.tsx
> +      <Header />
Добавила Header в App.tsx

2022-07-21 18:19 UTC, ravgusha commented on src/containers/AddContact/index.tsx
> +    <>
после реорганизации структуры, фрагменты стали не нужны, удалила

2022-07-21 18:21 UTC, ravgusha commented on src/containers/AddContact/index.tsx
> +const AddPage = () => {
Перенесла некоторые компоненты в котейнеры для удобства

2022-07-24 16:48 UTC, ravgusha commented on src/containers/AddContact/index.tsx
> +      <Container>
Перенесла контейнер из контейнера в компонент

2022-07-25 10:01 UTC, ravgusha commented on src/containers/AddContact/index.tsx
> +          <Input placeholder="First name" {...register('firstName', { required: true })} />
Вынесла инпут в отдельный компонент

2022-07-27 11:21 UTC, ravgusha commented on src/containers/AddContact/index.tsx
> +          {errors.firstName?.type === 'required' && <Error>First name is required</Error>}
Сделала сообщение об ошибке отдельным компонентом

2022-07-27 11:56 UTC, ravgusha commented on src/redux/types.ts
> +import { IPerson } from "../types";
Перенесла интерфейс в место получения данных

2022-07-27 12:03 UTC, ravgusha commented on src/components/Header/Header.tsx
> +const MainButton = styled.button`
главная кнопка это был логотип. Вынесла в отдельный компонент

2022-07-28 19:14 UTC, merged